@startuml
'https://plantuml.com/class-diagram

class type {
}

metaclass MetaBorg {
    - {field} state
    - {method} call(cls, *args, **kwargs)
    - {method} check_args(cls, *args, **kwargs)

}

class SharedStateManager {
    {field} value: Any
}

class SharedStateSubManager {
}

type <|-- MetaBorg
MetaBorg <-- SharedStateManager : use as metaclass
SharedStateManager <|- SharedStateSubManager

@enduml