# Generated by Django 5.1.7 on 2025-03-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_alter_group_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(db_index=True, max_length=30, verbose_name='Lastname')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'ordering': ['lastname'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Name'),
        ),
    ]
