# Generated by Django 5.1.7 on 2025-03-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_person_group_comment_alter_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='firstname',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Firstname'),
        ),
    ]
