# Generated by Django 5.1.7 on 2025-03-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_person_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Comment'),
        ),
    ]
