# Generated by Django 5.1.7 on 2025-03-28 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_person_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.SlugField(blank=True, default=None, null=True, verbose_name='Username'),
        ),
        migrations.AddField(
            model_name='person',
            name='website',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='person',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(20)], verbose_name='Comment'),
        ),
    ]
