# Generated by Django 5.1.7 on 2025-03-29 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_person_email_person_username_person_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='height',
            field=models.IntegerField(blank=True, default=None, help_text='cm', null=True, validators=[django.core.validators.MinValueValidator(150), django.core.validators.MaxValueValidator(250)], verbose_name='Height'),
        ),
    ]
