# Generated by Django 5.1.7 on 2025-03-29 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_person_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Salary'),
        ),
        migrations.AddField(
            model_name='person',
            name='weight',
            field=models.FloatField(blank=True, default=None, help_text='kg', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(150)], verbose_name='Weight'),
        ),
    ]
