# Generated by Django 5.1.7 on 2025-03-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_person_salary_person_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birthdate',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Birthdate'),
        ),
        migrations.AddField(
            model_name='person',
            name='currency',
            field=models.IntegerField(choices=[(10, 'USD'), (20, 'PLN')], default=20, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='person',
            name='duration',
            field=models.DurationField(blank=True, default=None, null=True, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='person',
            name='language',
            field=models.CharField(choices=[('pl', 'Polish'), ('en', 'English')], default='pl', max_length=2, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='person',
            name='since',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Since'),
        ),
        migrations.AddField(
            model_name='person',
            name='wakeup',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Wakeup'),
        ),
    ]
