# Generated by Django 5.1.7 on 2025-03-29 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_person_birthdate_person_currency_person_duration_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Role',
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'verbose_name': 'Role', 'verbose_name_plural': 'Role'},
        ),
        migrations.AddField(
            model_name='person',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='persons', to='demo.role', verbose_name='Roles'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Street')),
                ('city', models.CharField(max_length=20, verbose_name='City')),
                ('postcode', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Postcode')),
                ('country', models.CharField(max_length=20, verbose_name='Country')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='demo.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'ordering': ['country', 'city'],
            },
        ),
    ]
