# Generated by Django 5.1.7 on 2025-03-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0010_rename_group_role_alter_role_options_person_roles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='firstname',
            field=models.CharField(max_length=30, verbose_name='Firstname'),
        ),
    ]
