# Generated by Django 5.1.7 on 2025-03-29 19:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0011_alter_person_firstname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='UTC Date and Time', verbose_name='Created Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='created_user',
            field=models.ForeignKey(blank=True, help_text='User', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created User'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Is record deleted?', verbose_name='Is Deleted?'),
        ),
        migrations.AddField(
            model_name='person',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, help_text='UTC Date and Time', verbose_name='Modified Date'),
        ),
        migrations.AddField(
            model_name='person',
            name='modified_user',
            field=models.ForeignKey(blank=True, help_text='User', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified User'),
        ),
        migrations.AddField(
            model_name='role',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='UTC Date and Time', verbose_name='Created Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='created_user',
            field=models.ForeignKey(blank=True, help_text='User', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created User'),
        ),
        migrations.AddField(
            model_name='role',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Is record deleted?', verbose_name='Is Deleted?'),
        ),
        migrations.AddField(
            model_name='role',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, help_text='UTC Date and Time', verbose_name='Modified Date'),
        ),
        migrations.AddField(
            model_name='role',
            name='modified_user',
            field=models.ForeignKey(blank=True, help_text='User', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified User'),
        ),
    ]
