@startuml
!include ../../styles.puml
'https://plantuml.com/class-diagram

title Callback Design Pattern Documentation

header
    The Callback Pattern allows for asynchronous execution and event-driven
    programming. It involves passing a function as an argument to another function,
    which is then executed when a specific event occurs or when the operation completes.
endheader

class CallbackExecutor {
    {method} execute(data: Any, on_success: Callable, on_error: Callable): None
}

class Client {
    {method} process_data(data: Any): None
    {method} on_success(result: Any): None
    {method} on_error(error: Exception): None
}

Client <-- CallbackExecutor : uses

@enduml