#!/usr/bin/env python3
# https://python3.info/artificial-intelligence/about/index.html


# %% AI About
# - Jakie są dostępne modele językowe,
# - Który model wybrać,
# - Jak tworzyć kod używając modeli językowych,
# - Jakie edytory kodu oraz IDE wspierają tworzenie kodu przez AI,
# - Jak weryfikować czy wygenerowany kod jest poprawny,
# - Jak tworzyć testy do napisanego kodu,
# - Jak refaktorować kod napisany przez AI,
# - Jak AI może refaktorować kos napisny przez Ciebie.
# %%



# %% Available language models
# - https://artificialanalysis.ai/leaderboards/models
# - https://github.com/marketplace/models
# - Copilot
# - ChatGPT (GPT-4o)
# - Tabnine (has offline version)
# - Codeium (free)
# - Claude Sonnet 3.5
# - Jetbrains AI Assistant
# - Mistral
# - Gemini 1.0, 1.5, 2.0
# - Replit
# %%



# %% Copilot
# - Source: https://en.wikipedia.org/wiki/GitHub_Copilot
# %%



# %% Choosing a model
# - Why choose one model over another
# - Metrics to consider when choosing a model
# - How to evaluate a model
# %%



# %% Creating code using language models
# - Autocomplete
# - Code generation
# - Chat-based code generation
# %%



# %% IDEs and code editors that support AI code generation
# - PyCharm
# - VS Code
# - Zed
# %%



# %% Verifying generated code
# - How to verify that generated code is correct
# - Hallucinations in generated code
# - Most common errors in generated code
# - Weakest points of AI-generated code
# %%



# %% Creating tests for generated code
# - Types of tests (unit, integration, end-to-end)
# - Testing frameworks
# - Cyclomatic complexity and code coverage
# - Mutation testing
# - Development tools ecosystem and CI/CD pipeline
# - How to create tests for generated code
# - How to test generated code
# - How to test AI-generated code
# - AI-generated tests
# %%



# %% Refactoring code generated by AI
# %%



# %% Refactoring code written by you using AI
# %%



# %% Further Reading
# - https://artificialanalysis.ai/leaderboards/models
# - https://github.com/marketplace/models
# - Monster API playground <https://monsterapi.ai/playground>__
# %%



