@startuml
!include ../../styles.puml
'https://plantuml.com/class-diagram

title Singleton Design Pattern Documentation

header
    The Singleton Pattern ensures that a class has only one instance and provides
    a global point of access to that instance. It restricts the instantiation of
    a class to one object, which can be useful for managing shared resources or
    coordinating actions across a system.
endheader

class type {
}

metaclass Singleton {
    - {field} instance
    __call__(cls, *args, **kwargs)
}

class ConfigManager {
    - {field} settings: dict
    {method} get()
    {method} set()
    {method} pop()
}

type <|-- Singleton
Singleton <-- ConfigManager : use as metaclass


@enduml